#
# Travis Setup
#

# use ubuntu trusty for newer version of nodejs, used for JS testing
dist: trusty

# faster builds on new travis setup not using sudo
sudo: false
group: edge

language: php

php:
  - 7.1
  - 7.2

env:
  global:
    - DEFAULT_COMPOSER_FLAGS="--prefer-dist --no-interaction --no-progress --optimize-autoloader"
    - TASK_TESTS_PHP=1
    - TASK_TESTS_COVERAGE=1

# cache vendor dirs
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  # install composer dependencies
  - travis_retry composer self-update
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer global require hirak/prestissimo
  - travis_retry composer global require fxp/composer-asset-plugin
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
  - travis_retry composer install $DEFAULT_COMPOSER_FLAGS

before_script:
  # show some versions and env information
  - php --version
  - composer --version
  - |
    if [ $TASK_TESTS_PHP == 1 ]; then
      php -r "echo INTL_ICU_VERSION . \"\n\";"
      php -r "echo INTL_ICU_DATA_VERSION . \"\n\";"
    fi

  # enable code coverage
  - |
    if [ $TASK_TESTS_COVERAGE == 1 ]; then
      CODECEPTION_FLAGS="--coverage-xml"
    fi

  - vendor/bin/codecept build

script:
  # PHP tests
  - vendor/bin/codecept --verbose run $CODECEPTION_FLAGS
  # CodeSniffer
  - vendor/bin/phpcs --extensions=php .

after_script:
  - |
    if [ $TASK_TESTS_COVERAGE == 1 ]; then
      travis_retry php vendor/bin/php-coveralls
    fi